
messages:
  noPermission: "&#dc143cУ вас недостаточно прав для выполнения этого действия!"
  reloaded: "&#00ff7fПлагин успешно перезагружен"

# Плейсхолдер - %worldplaceholder%
# Будет выглядеть как &#c0c0c0◆
worldSymbol: "◆"
# Стандартный цвет, используется для миров, которые не указаны ниже
defaultColor: "&#c0c0c0"

# Можно использовать как HEX цвета в формате &#abcdef, так и обычные цвета через &a
worlds:
  world: "&#00ff7f"
  world_nether: "&#dc143c"
  world_the_end: "&#8a2be2"
